services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    ports:
      - "7474:7474"  # Web Interface
      - "7687:7687"  # Bolt Protocol
    environment:
      NEO4J_AUTH: neo4j/password  # Default username: neo4j, password: password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf

  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      # Setting access credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5000:5432"  # Host Port Changed to 5000, prevents conflict with PgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  postgres_data: